### ISSUE TITLE
Invalid Syntax L69

### ISSUE THREAD

**Issue by stevenjdunn** [rpbap/CADECT#1]
Hi - I was interested in testing this tool as the preprint sounds like it's a great fit for my needs, but I get an error when running:

`  File "CADECTv1.0.2.py", line 69
    table_file.write(f"{record.id}\t{classification}\t{num_windows}\t{num_overlaps}\n")
                                                                                     ^
SyntaxError: invalid syntax`

Running Python 3.5.5, installed using instructions on the readme.

Thanks!

**Comment by rpbap** [comment]
Hi Steven! Thanks for reaching out!
The error you're encountering is likely due to a version of Python that doesn't support f-strings. F-strings (formatted string literals) were introduced in Python 3.6, so if you're using an older version of Python, you would encounter a SyntaxError.

I just updated the README to clarify that. =)

If you are not able to get 3.6 or higher, you can modify the script on Line 116: 

"table_file.write(f"{record.id}\t{classification}\t{num_windows}\t{num_overlaps}\n"

for 

"table_file.write("{}\t{}\t{}\t{}\n".format(record.id, classification, num_windows, num_overlaps))"

Let me know if this works for you
